export type StyleDefault = {
  name: string;
  category: 'fade' | 'taper' | 'classic' | 'natural' | 'beard';
  sortOrder: number;
};

export const SHOP_TYPES = [
  { value: 'uk_general',        label: 'UK General' },
  { value: 'afro',              label: 'Afro / Black Hair' },
  { value: 'turkish',           label: 'Turkish' },
  { value: 'indian',            label: 'Indian' },
  { value: 'caribbean',         label: 'Caribbean' },
  { value: 'eastern_european',  label: 'Eastern European' },
  { value: 'east_asian',        label: 'East Asian (Korean / Japanese)' },
] as const;

export type ShopType = typeof SHOP_TYPES[number]['value'];

const UK_GENERAL: StyleDefault[] = [
  { name: 'Skin Fade',      category: 'fade',    sortOrder: 0 },
  { name: 'High Fade',      category: 'fade',    sortOrder: 1 },
  { name: 'Mid Fade',       category: 'fade',    sortOrder: 2 },
  { name: 'Low Fade',       category: 'fade',    sortOrder: 3 },
  { name: 'Taper Fade',     category: 'fade',    sortOrder: 4 },
  { name: 'Drop Fade',      category: 'fade',    sortOrder: 5 },
  { name: 'Burst Fade',     category: 'fade',    sortOrder: 6 },
  { name: 'Scissor Cut',    category: 'classic', sortOrder: 7 },
  { name: 'Textured Crop',  category: 'classic', sortOrder: 8 },
  { name: 'French Crop',    category: 'classic', sortOrder: 9 },
  { name: 'Buzz Cut',       category: 'classic', sortOrder: 10 },
  { name: 'Crew Cut',       category: 'classic', sortOrder: 11 },
  { name: 'Quiff',          category: 'classic', sortOrder: 12 },
  { name: 'Slick Back',     category: 'classic', sortOrder: 13 },
  { name: 'Pompadour',      category: 'classic', sortOrder: 14 },
  { name: 'Undercut',       category: 'classic', sortOrder: 15 },
  { name: 'Faux Hawk',      category: 'classic', sortOrder: 16 },
  { name: 'Side Part',      category: 'classic', sortOrder: 17 },
  { name: 'Not done',       category: 'beard',   sortOrder: 0 },
  { name: 'Shape Up',       category: 'beard',   sortOrder: 1 },
  { name: 'Beard Trim',     category: 'beard',   sortOrder: 2 },
  { name: 'Beard Fade',     category: 'beard',   sortOrder: 3 },
  { name: 'Full Beard',     category: 'beard',   sortOrder: 4 },
  { name: 'Goatee',         category: 'beard',   sortOrder: 5 },
  { name: 'Hot Towel Shave', category: 'beard',  sortOrder: 6 },
];

const AFRO: StyleDefault[] = [
  { name: 'Skin Fade',         category: 'fade',    sortOrder: 0 },
  { name: 'High Fade',         category: 'fade',    sortOrder: 1 },
  { name: 'Mid Fade',          category: 'fade',    sortOrder: 2 },
  { name: 'Low Fade',          category: 'fade',    sortOrder: 3 },
  { name: 'Burst Fade',        category: 'fade',    sortOrder: 4 },
  { name: 'Temp Fade',         category: 'fade',    sortOrder: 5 },
  { name: 'Taper Fade',        category: 'fade',    sortOrder: 6 },
  { name: 'Flat Top',          category: 'classic', sortOrder: 7 },
  { name: 'High Top',          category: 'classic', sortOrder: 8 },
  { name: 'Crew Cut',          category: 'classic', sortOrder: 9 },
  { name: 'Afro',              category: 'natural', sortOrder: 10 },
  { name: 'Short Afro',        category: 'natural', sortOrder: 11 },
  { name: '360 Waves',         category: 'natural', sortOrder: 12 },
  { name: 'Sponge Twists',     category: 'natural', sortOrder: 13 },
  { name: 'Two-Strand Twists', category: 'natural', sortOrder: 14 },
  { name: 'Cornrows',          category: 'natural', sortOrder: 15 },
  { name: 'Dreadlocks',        category: 'natural', sortOrder: 16 },
  { name: 'Curly Top',         category: 'natural', sortOrder: 17 },
  { name: 'Curly Afro Fade',   category: 'natural', sortOrder: 18 },
  { name: 'Not done',          category: 'beard',   sortOrder: 0 },
  { name: 'Beard Fade',        category: 'beard',   sortOrder: 1 },
  { name: 'Full Beard',        category: 'beard',   sortOrder: 2 },
  { name: 'Short Beard',       category: 'beard',   sortOrder: 3 },
  { name: 'Goatee',            category: 'beard',   sortOrder: 4 },
  { name: 'Shape Up',          category: 'beard',   sortOrder: 5 },
  { name: 'Beard + Hard Part', category: 'beard',   sortOrder: 6 },
];

const TURKISH: StyleDefault[] = [
  { name: 'Skin Fade',    category: 'fade',    sortOrder: 0 },
  { name: 'High Fade',    category: 'fade',    sortOrder: 1 },
  { name: 'Mid Fade',     category: 'fade',    sortOrder: 2 },
  { name: 'Low Fade',     category: 'fade',    sortOrder: 3 },
  { name: 'Taper Fade',   category: 'taper',   sortOrder: 4 },
  { name: 'Hard Part',    category: 'taper',   sortOrder: 5 },
  { name: 'Slick Back',   category: 'classic', sortOrder: 6 },
  { name: 'Pompadour',    category: 'classic', sortOrder: 7 },
  { name: 'Quiff',        category: 'classic', sortOrder: 8 },
  { name: 'Comb-Over',    category: 'classic', sortOrder: 9 },
  { name: 'Side Part',    category: 'classic', sortOrder: 10 },
  { name: 'Undercut',     category: 'classic', sortOrder: 11 },
  { name: 'Scissor Cut',  category: 'classic', sortOrder: 12 },
  { name: 'Textured Crop',category: 'classic', sortOrder: 13 },
  { name: 'Not done',     category: 'beard',   sortOrder: 0 },
  { name: 'Full Beard',   category: 'beard',   sortOrder: 1 },
  { name: 'Short Beard',  category: 'beard',   sortOrder: 2 },
  { name: 'Beard Fade',   category: 'beard',   sortOrder: 3 },
  { name: 'Goatee',       category: 'beard',   sortOrder: 4 },
  { name: 'Mustache',     category: 'beard',   sortOrder: 5 },
  { name: 'Hot Towel Shave', category: 'beard', sortOrder: 6 },
];

const INDIAN: StyleDefault[] = [
  { name: 'High Fade',     category: 'fade',    sortOrder: 0 },
  { name: 'Mid Fade',      category: 'fade',    sortOrder: 1 },
  { name: 'Low Fade',      category: 'fade',    sortOrder: 2 },
  { name: 'Skin Fade',     category: 'fade',    sortOrder: 3 },
  { name: 'Taper Fade',    category: 'taper',   sortOrder: 4 },
  { name: 'Low Taper',     category: 'taper',   sortOrder: 5 },
  { name: 'Quiff',         category: 'classic', sortOrder: 6 },
  { name: 'Slick Back',    category: 'classic', sortOrder: 7 },
  { name: 'Comb-Over',     category: 'classic', sortOrder: 8 },
  { name: 'Side Part',     category: 'classic', sortOrder: 9 },
  { name: 'Pompadour',     category: 'classic', sortOrder: 10 },
  { name: 'Textured Crop', category: 'classic', sortOrder: 11 },
  { name: 'Undercut',      category: 'classic', sortOrder: 12 },
  { name: 'Scissor Cut',   category: 'classic', sortOrder: 13 },
  { name: 'Not done',      category: 'beard',   sortOrder: 0 },
  { name: 'Beard Trim',    category: 'beard',   sortOrder: 1 },
  { name: 'Full Beard',    category: 'beard',   sortOrder: 2 },
  { name: 'Goatee',        category: 'beard',   sortOrder: 3 },
  { name: 'Short Beard',   category: 'beard',   sortOrder: 4 },
  { name: 'Beard Fade',    category: 'beard',   sortOrder: 5 },
];

const CARIBBEAN: StyleDefault[] = [
  { name: 'Skin Fade',          category: 'fade',    sortOrder: 0 },
  { name: 'High Fade',          category: 'fade',    sortOrder: 1 },
  { name: 'Mid Fade',           category: 'fade',    sortOrder: 2 },
  { name: 'Low Fade',           category: 'fade',    sortOrder: 3 },
  { name: 'Burst Fade',         category: 'fade',    sortOrder: 4 },
  { name: 'Temp Fade',          category: 'fade',    sortOrder: 5 },
  { name: 'Skin Fade + Design', category: 'fade',    sortOrder: 6 },
  { name: 'High Top',           category: 'classic', sortOrder: 7 },
  { name: 'Flat Top',           category: 'classic', sortOrder: 8 },
  { name: 'Afro',               category: 'natural', sortOrder: 9 },
  { name: '360 Waves',          category: 'natural', sortOrder: 10 },
  { name: 'Dread Maintenance',  category: 'natural', sortOrder: 11 },
  { name: 'Sponge Twists',      category: 'natural', sortOrder: 12 },
  { name: 'Cornrows',           category: 'natural', sortOrder: 13 },
  { name: 'Carved Patterns',    category: 'natural', sortOrder: 14 },
  { name: 'Not done',           category: 'beard',   sortOrder: 0 },
  { name: 'Beard Fade',         category: 'beard',   sortOrder: 1 },
  { name: 'Full Beard',         category: 'beard',   sortOrder: 2 },
  { name: 'Short Beard',        category: 'beard',   sortOrder: 3 },
  { name: 'Goatee',             category: 'beard',   sortOrder: 4 },
  { name: 'Shape Up',           category: 'beard',   sortOrder: 5 },
];

const EASTERN_EUROPEAN: StyleDefault[] = [
  { name: 'High Fade',     category: 'fade',    sortOrder: 0 },
  { name: 'Mid Fade',      category: 'fade',    sortOrder: 1 },
  { name: 'Low Fade',      category: 'fade',    sortOrder: 2 },
  { name: 'Skin Fade',     category: 'fade',    sortOrder: 3 },
  { name: 'Hard Part',     category: 'taper',   sortOrder: 4 },
  { name: 'Taper Fade',    category: 'taper',   sortOrder: 5 },
  { name: 'Buzz Cut',      category: 'classic', sortOrder: 6 },
  { name: 'Crew Cut',      category: 'classic', sortOrder: 7 },
  { name: 'Slick Back',    category: 'classic', sortOrder: 8 },
  { name: 'Comb-Over',     category: 'classic', sortOrder: 9 },
  { name: 'Side Part',     category: 'classic', sortOrder: 10 },
  { name: 'Scissor Cut',   category: 'classic', sortOrder: 11 },
  { name: 'Not done',      category: 'beard',   sortOrder: 0 },
  { name: 'Short Beard',   category: 'beard',   sortOrder: 1 },
  { name: 'Full Beard',    category: 'beard',   sortOrder: 2 },
  { name: 'Beard Trim',    category: 'beard',   sortOrder: 3 },
  { name: 'Goatee',        category: 'beard',   sortOrder: 4 },
];

const EAST_ASIAN: StyleDefault[] = [
  { name: 'Two-Block Cut',         category: 'classic', sortOrder: 0 },
  { name: 'Korean Wolf Cut',       category: 'classic', sortOrder: 1 },
  { name: 'Korean Comma Hair',     category: 'classic', sortOrder: 2 },
  { name: 'Korean Middle Part',    category: 'classic', sortOrder: 3 },
  { name: 'Japanese Textured Crop',category: 'classic', sortOrder: 4 },
  { name: 'Japanese Undercut',     category: 'classic', sortOrder: 5 },
  { name: 'Japanese Messy Crop',   category: 'classic', sortOrder: 6 },
  { name: 'Side Swept',            category: 'classic', sortOrder: 7 },
  { name: 'Slick Back',            category: 'classic', sortOrder: 8 },
  { name: 'Spiky',                 category: 'classic', sortOrder: 9 },
  { name: 'Mid Fade',              category: 'fade',    sortOrder: 10 },
  { name: 'Low Fade',              category: 'fade',    sortOrder: 11 },
  { name: 'High Fade',             category: 'fade',    sortOrder: 12 },
  { name: 'Not done',              category: 'beard',   sortOrder: 0 },
  { name: 'Short Beard',           category: 'beard',   sortOrder: 1 },
  { name: 'Goatee',                category: 'beard',   sortOrder: 2 },
];

export const STYLE_DEFAULTS: Record<ShopType, StyleDefault[]> = {
  uk_general:       UK_GENERAL,
  afro:             AFRO,
  turkish:          TURKISH,
  indian:           INDIAN,
  caribbean:        CARIBBEAN,
  eastern_european: EASTERN_EUROPEAN,
  east_asian:       EAST_ASIAN,
};
