ALTER TABLE "WalkIn" ADD COLUMN IF NOT EXISTS "isAway" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "WalkIn" ADD COLUMN IF NOT EXISTS "returnByMinutes" INTEGER;
ALTER TABLE "WalkIn" ADD COLUMN IF NOT EXISTS "queueReminderSentAt" TIMESTAMP(3);
